/**
 * seed.ts — the pre-loaded exercise library.
 *
 * These exercises are inserted into IndexedDB the first time the app runs on
 * a device. IDs are stable slugs (not random UUIDs) so that if we ever need
 * to migrate seed data we can reference them reliably.
 *
 * isCustom: false means the app seeded it. The user can still edit or delete
 * any exercise — this is a single-user app and you should have full control.
 */

import type { Exercise } from './db'

const SEED_DATE = '2025-01-01T00:00:00.000Z'

function seed(
  name: string,
  category: Exercise['category'],
  muscleGroup: string,
): Exercise {
  return {
    id: 'seed-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-$/, ''),
    name,
    category,
    muscleGroup,
    isCustom: false,
    videoUrl: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
    syncedAt: null,
    deleted: false,
  }
}

export const seedExercises: Exercise[] = [

  // ── Barbell ────────────────────────────────────────────────────────────────

  seed('Back Squat',             'barbell', 'Quads'),
  seed('Front Squat',            'barbell', 'Quads'),
  seed('Box Squat',              'barbell', 'Quads'),
  seed('Zercher Squat',          'barbell', 'Quads'),
  seed('Barbell Lunge',          'barbell', 'Quads'),
  seed('Bench Press',            'barbell', 'Chest'),
  seed('Incline Bench Press',    'barbell', 'Chest'),
  seed('Decline Bench Press',    'barbell', 'Chest'),
  seed('Close-Grip Bench Press', 'barbell', 'Triceps'),
  seed('Deadlift',               'barbell', 'Back'),
  seed('Romanian Deadlift',      'barbell', 'Hamstrings'),
  seed('Sumo Deadlift',          'barbell', 'Quads'),
  seed('Stiff-Leg Deadlift',     'barbell', 'Hamstrings'),
  seed('Overhead Press',         'barbell', 'Shoulders'),
  seed('Push Press',             'barbell', 'Shoulders'),
  seed('Barbell Row',            'barbell', 'Back'),
  seed('Pendlay Row',            'barbell', 'Back'),
  seed('Barbell Hip Thrust',     'barbell', 'Glutes'),
  seed('Good Morning',           'barbell', 'Hamstrings'),
  seed('Barbell Curl',           'barbell', 'Biceps'),
  seed('Barbell Skullcrusher',   'barbell', 'Triceps'),
  seed('Barbell Shrug',          'barbell', 'Traps'),
  seed('Upright Row',            'barbell', 'Shoulders'),
  seed('Power Clean',            'barbell', 'Full Body'),
  seed('Hang Power Clean',       'barbell', 'Full Body'),
  seed('Power Snatch',           'barbell', 'Full Body'),
  seed('Safety Bar Squat',       'barbell', 'Quads'),
  seed('Pause Squat',            'barbell', 'Quads'),
  seed('Barbell Step-Up',        'barbell', 'Quads'),
  seed('Barbell Bulgarian Split Squat', 'barbell', 'Quads'),
  seed('Barbell Calf Raise',     'barbell', 'Calves'),
  seed('Landmine Press',         'barbell', 'Shoulders'),
  seed('Landmine Row',           'barbell', 'Back'),
  seed('Landmine Squat',         'barbell', 'Quads'),
  seed('JM Press',               'barbell', 'Triceps'),
  seed('Spoto Press',            'barbell', 'Chest'),
  seed('Floor Press',            'barbell', 'Chest'),
  seed('Pin Press',              'barbell', 'Chest'),
  seed('Rack Pull',              'barbell', 'Back'),
  seed('Deficit Deadlift',       'barbell', 'Back'),
  seed('Barbell Glute Bridge',   'barbell', 'Glutes'),
  seed('Barbell Good Morning',   'barbell', 'Hamstrings'),
  seed('Barbell Hack Squat',     'barbell', 'Quads'),

  // ── Dumbbell ───────────────────────────────────────────────────────────────

  seed('Dumbbell Bench Press',         'dumbbell', 'Chest'),
  seed('Incline Dumbbell Press',       'dumbbell', 'Chest'),
  seed('Dumbbell Fly',                 'dumbbell', 'Chest'),
  seed('Incline Dumbbell Fly',         'dumbbell', 'Chest'),
  seed('Dumbbell Pullover',            'dumbbell', 'Back'),
  seed('Dumbbell Shoulder Press',      'dumbbell', 'Shoulders'),
  seed('Arnold Press',                 'dumbbell', 'Shoulders'),
  seed('Lateral Raise',                'dumbbell', 'Shoulders'),
  seed('Front Raise',                  'dumbbell', 'Shoulders'),
  seed('Bent-Over Lateral Raise',      'dumbbell', 'Shoulders'),
  seed('Single-Arm Dumbbell Row',      'dumbbell', 'Back'),
  seed('Dumbbell Curl',                'dumbbell', 'Biceps'),
  seed('Hammer Curl',                  'dumbbell', 'Biceps'),
  seed('Concentration Curl',           'dumbbell', 'Biceps'),
  seed('Incline Dumbbell Curl',        'dumbbell', 'Biceps'),
  seed('Dumbbell Tricep Extension',    'dumbbell', 'Triceps'),
  seed('Dumbbell Kickback',            'dumbbell', 'Triceps'),
  seed('Dumbbell Romanian Deadlift',   'dumbbell', 'Hamstrings'),
  seed('Goblet Squat',                 'dumbbell', 'Quads'),
  seed('Dumbbell Lunge',               'dumbbell', 'Quads'),
  seed('Dumbbell Reverse Lunge',       'dumbbell', 'Quads'),
  seed('Dumbbell Step-Up',             'dumbbell', 'Quads'),
  seed('Dumbbell Hip Thrust',          'dumbbell', 'Glutes'),
  seed('Dumbbell Shrug',               'dumbbell', 'Traps'),
  seed('Dumbbell Calf Raise',          'dumbbell', 'Calves'),
  seed('Dumbbell Wrist Curl',               'dumbbell', 'Forearms'),
  seed('Dumbbell Bulgarian Split Squat',    'dumbbell', 'Quads'),
  seed('Dumbbell Sumo Squat',               'dumbbell', 'Quads'),
  seed('Dumbbell Box Step-Up',              'dumbbell', 'Quads'),
  seed('Dumbbell Chest-Supported Row',      'dumbbell', 'Back'),
  seed('Dumbbell Seal Row',                 'dumbbell', 'Back'),
  seed('Spider Curl',                       'dumbbell', 'Biceps'),
  seed('Prone Incline Curl',                'dumbbell', 'Biceps'),
  seed('Dumbbell Floor Press',              'dumbbell', 'Chest'),
  seed('Dumbbell Skull Crusher',            'dumbbell', 'Triceps'),
  seed('Dumbbell JM Press',                 'dumbbell', 'Triceps'),
  seed('Dumbbell Reverse Curl',             'dumbbell', 'Forearms'),
  seed('Farmers Carry',                     'dumbbell', 'Full Body'),
  seed('Dumbbell Romanian Split Squat',     'dumbbell', 'Hamstrings'),
  seed('Dumbbell Seated Calf Raise',        'dumbbell', 'Calves'),

  // ── Machine ────────────────────────────────────────────────────────────────

  seed('Leg Press',              'machine', 'Quads'),
  seed('Hack Squat Machine',     'machine', 'Quads'),
  seed('Leg Extension',          'machine', 'Quads'),
  seed('Seated Leg Curl',        'machine', 'Hamstrings'),
  seed('Lying Leg Curl',         'machine', 'Hamstrings'),
  seed('Seated Calf Raise',      'machine', 'Calves'),
  seed('Standing Calf Raise',    'machine', 'Calves'),
  seed('Leg Abductor',           'machine', 'Glutes'),
  seed('Leg Adductor',           'machine', 'Inner Thigh'),
  seed('Chest Press Machine',    'machine', 'Chest'),
  seed('Pec Dec',                'machine', 'Chest'),
  seed('Shoulder Press Machine', 'machine', 'Shoulders'),
  seed('Lat Pulldown Machine',   'machine', 'Back'),
  seed('Seated Row Machine',     'machine', 'Back'),
  seed('Chest-Supported Row',    'machine', 'Back'),
  seed('Pullover Machine',       'machine', 'Back'),
  seed('Back Extension Machine', 'machine', 'Lower Back'),
  seed('Ab Crunch Machine',      'machine', 'Core'),
  seed('Smith Machine Squat',    'machine', 'Quads'),
  seed('Assisted Pull-Up',       'machine', 'Back'),
  seed('Assisted Dip',                'machine', 'Chest'),
  seed('Reverse Hyper',               'machine', 'Glutes'),
  seed('GHD Sit-Up',                  'machine', 'Core'),
  seed('GHD Hip Extension',           'machine', 'Hamstrings'),
  seed('Leg Press Calf Raise',        'machine', 'Calves'),
  seed('Preacher Curl Machine',       'machine', 'Biceps'),
  seed('T-Bar Row',                   'machine', 'Back'),
  seed('Seated Hip Abduction',        'machine', 'Glutes'),
  seed('Seated Hip Adduction',        'machine', 'Inner Thigh'),
  seed('Chest Fly Machine',           'machine', 'Chest'),
  seed('Pendulum Squat',              'machine', 'Quads'),
  seed('Belt Squat',                  'machine', 'Quads'),
  seed('Rowing Machine (Ergometer)',  'machine', 'Full Body'),
  seed('Ski Erg',                     'machine', 'Full Body'),
  seed('Assault Bike',                'machine', 'Cardio'),

  // ── Cable ──────────────────────────────────────────────────────────────────

  seed('Cable Row (Seated)',           'cable', 'Back'),
  seed('Cable Row (Standing)',         'cable', 'Back'),
  seed('Cable Lat Pulldown',          'cable', 'Back'),
  seed('Straight-Arm Pulldown',       'cable', 'Back'),
  seed('Cable Fly (Low to High)',     'cable', 'Chest'),
  seed('Cable Fly (High to Low)',     'cable', 'Chest'),
  seed('Cable Fly (Mid)',             'cable', 'Chest'),
  seed('Cable Curl (Straight Bar)',   'cable', 'Biceps'),
  seed('Cable Curl (Rope)',           'cable', 'Biceps'),
  seed('Cable Curl (Single Arm)',     'cable', 'Biceps'),
  seed('Cable Tricep Pushdown (Rope)','cable', 'Triceps'),
  seed('Cable Tricep Pushdown (Bar)', 'cable', 'Triceps'),
  seed('Cable Overhead Extension',    'cable', 'Triceps'),
  seed('Cable Face Pull',             'cable', 'Shoulders'),
  seed('Cable Lateral Raise',         'cable', 'Shoulders'),
  seed('Cable Upright Row',           'cable', 'Shoulders'),
  seed('Cable Reverse Fly',           'cable', 'Shoulders'),
  seed('Cable Kickback',              'cable', 'Triceps'),
  seed('Cable Pull-Through',          'cable', 'Glutes'),
  seed('Cable Hip Abduction',         'cable', 'Glutes'),
  seed('Cable Crunch',                'cable', 'Core'),
  seed('Cable Woodchop',              'cable', 'Core'),
  seed('Cable Hip Extension',         'cable', 'Glutes'),
  seed('Cable Glute Kickback',        'cable', 'Glutes'),
  seed('Single-Arm Cable Row',        'cable', 'Back'),
  seed('Single-Arm Cable Press',      'cable', 'Chest'),
  seed('Half-Kneeling Cable Chop',    'cable', 'Core'),
  seed('Cable Romanian Deadlift',     'cable', 'Hamstrings'),
  seed('Cable Squat',                 'cable', 'Quads'),
  seed('Cable Shrug',                 'cable', 'Traps'),
  seed('Cable Preacher Curl',         'cable', 'Biceps'),
  seed('Cable Wrist Curl',            'cable', 'Forearms'),
  seed('Low Cable Fly',               'cable', 'Chest'),

  // ── Bodyweight ─────────────────────────────────────────────────────────────

  seed('Pull-Up',             'bodyweight', 'Back'),
  seed('Chin-Up',             'bodyweight', 'Back'),
  seed('Neutral-Grip Pull-Up','bodyweight', 'Back'),
  seed('Inverted Row',        'bodyweight', 'Back'),
  seed('Push-Up',             'bodyweight', 'Chest'),
  seed('Wide Push-Up',        'bodyweight', 'Chest'),
  seed('Diamond Push-Up',     'bodyweight', 'Triceps'),
  seed('Pike Push-Up',        'bodyweight', 'Shoulders'),
  seed('Archer Push-Up',      'bodyweight', 'Chest'),
  seed('Chest Dip',           'bodyweight', 'Chest'),
  seed('Tricep Dip',          'bodyweight', 'Triceps'),
  seed('Plank',               'bodyweight', 'Core'),
  seed('Side Plank',          'bodyweight', 'Core'),
  seed('Hollow Body Hold',    'bodyweight', 'Core'),
  seed('Crunch',              'bodyweight', 'Core'),
  seed('Sit-Up',              'bodyweight', 'Core'),
  seed('Leg Raise',           'bodyweight', 'Core'),
  seed('Hanging Leg Raise',   'bodyweight', 'Core'),
  seed('Ab Wheel Rollout',    'bodyweight', 'Core'),
  seed('Glute Bridge',        'bodyweight', 'Glutes'),
  seed('Single-Leg Glute Bridge', 'bodyweight', 'Glutes'),
  seed('Hip Thrust (Bodyweight)', 'bodyweight', 'Glutes'),
  seed('Bodyweight Squat',    'bodyweight', 'Quads'),
  seed('Jump Squat',          'bodyweight', 'Quads'),
  seed('Lunge',               'bodyweight', 'Quads'),
  seed('Reverse Lunge',       'bodyweight', 'Quads'),
  seed('Walking Lunge',       'bodyweight', 'Quads'),
  seed('Step-Up',             'bodyweight', 'Quads'),
  seed('Nordic Curl',         'bodyweight', 'Hamstrings'),
  seed('Mountain Climber',    'bodyweight', 'Core'),
  seed('Burpee',              'bodyweight', 'Full Body'),
  seed('L-Sit',                       'bodyweight', 'Core'),
  seed('Pistol Squat',                'bodyweight', 'Quads'),
  seed('Shrimp Squat',                'bodyweight', 'Quads'),
  seed('Bulgarian Split Squat',       'bodyweight', 'Quads'),
  seed('Handstand Push-Up',           'bodyweight', 'Shoulders'),
  seed('Wall Handstand Hold',         'bodyweight', 'Shoulders'),
  seed('Muscle-Up',                   'bodyweight', 'Back'),
  seed('Dragon Flag',                 'bodyweight', 'Core'),
  seed('Hollow Body Rock',            'bodyweight', 'Core'),
  seed('Superman Hold',               'bodyweight', 'Lower Back'),
  seed('Back Extension',              'bodyweight', 'Lower Back'),
  seed('Box Jump',                    'bodyweight', 'Quads'),
  seed('Broad Jump',                  'bodyweight', 'Full Body'),
  seed('Depth Jump',                  'bodyweight', 'Quads'),
  seed('Calf Raise (Bodyweight)',     'bodyweight', 'Calves'),
  seed('Single-Leg Calf Raise',       'bodyweight', 'Calves'),
  seed('Wall Sit',                    'bodyweight', 'Quads'),
  seed('Nordic Hamstring Curl',       'bodyweight', 'Hamstrings'),
  seed('Tuck Planche Hold',           'bodyweight', 'Chest'),
  seed('Front Lever Hold',            'bodyweight', 'Back'),

  // ── Cardio ─────────────────────────────────────────────────────────────────

  seed('Treadmill Run',       'cardio', 'Cardio'),
  seed('Treadmill Walk',      'cardio', 'Cardio'),
  seed('Outdoor Run',         'cardio', 'Cardio'),
  seed('Stationary Bike',     'cardio', 'Cardio'),
  seed('Outdoor Cycling',     'cardio', 'Cardio'),
  seed('Rowing Machine',      'cardio', 'Full Body'),
  seed('Elliptical',          'cardio', 'Cardio'),
  seed('Stair Climber',       'cardio', 'Cardio'),
  seed('Jump Rope',           'cardio', 'Cardio'),
  seed('Swimming',            'cardio', 'Full Body'),
  seed('Battle Ropes',          'cardio', 'Full Body'),
  seed('HIIT Cardio',           'cardio', 'Full Body'),
  seed('Sled Push',             'cardio', 'Full Body'),
  seed('Sled Pull',             'cardio', 'Full Body'),
  seed('Yoke Walk',             'cardio', 'Full Body'),
  seed('Sandbag Carry',         'cardio', 'Full Body'),
  seed('Hiking',                'cardio', 'Cardio'),
  seed('Sprint Intervals',      'cardio', 'Cardio'),
  seed('Versa Climber',         'cardio', 'Full Body'),
  seed('Hand Bike Ergometer',   'cardio', 'Cardio'),
  seed('Prowler Push',            'cardio', 'Full Body'),
  seed('Farmers Walk',            'cardio', 'Full Body'),
  seed('Boxing',                  'cardio', 'Full Body'),
  seed('Kickboxing',              'cardio', 'Full Body'),
  seed('Stadium Stairs',          'cardio', 'Cardio'),
  seed('Cycling Sprints',         'cardio', 'Cardio'),
  seed('Cross-Country Skiing',    'cardio', 'Full Body'),
  seed('Aqua Jogging',            'cardio', 'Cardio'),
  seed('Dance Cardio',            'cardio', 'Full Body'),
  seed('Treadmill Incline Walk',  'cardio', 'Cardio'),
  seed('Treadmill Hill Sprint',   'cardio', 'Cardio'),
  seed('Swimming Laps',           'cardio', 'Full Body'),

  // ── Additional Barbell ─────────────────────────────────────────────────────

  seed('Overhead Squat',          'barbell', 'Quads'),
  seed('Snatch-Grip Deadlift',    'barbell', 'Back'),
  seed('Paused Deadlift',         'barbell', 'Back'),
  seed('Barbell Walking Lunge',   'barbell', 'Quads'),
  seed('Bradford Press',          'barbell', 'Shoulders'),
  seed('Behind-the-Neck Press',   'barbell', 'Shoulders'),
  seed('Barbell Preacher Curl',   'barbell', 'Biceps'),
  seed('Barbell Drag Curl',       'barbell', 'Biceps'),
  seed('Barbell Reverse Curl',    'barbell', 'Forearms'),
  seed('Barbell Wrist Curl',      'barbell', 'Forearms'),
  seed('Barbell Rollout',         'barbell', 'Core'),
  seed('Barbell Pullover',        'barbell', 'Back'),
  seed('Barbell Reverse Lunge',   'barbell', 'Quads'),
  seed('Barbell Front Split Squat','barbell','Quads'),
  seed('Cambered Bar Squat',      'barbell', 'Quads'),
  seed('Barbell Lateral Lunge',   'barbell', 'Quads'),
  seed('Barbell Good Morning (Seated)', 'barbell', 'Hamstrings'),
  seed('Push Jerk',               'barbell', 'Full Body'),
  seed('Clean and Jerk',          'barbell', 'Full Body'),
  seed('Snatch',                  'barbell', 'Full Body'),
  seed('Barbell Z-Press',         'barbell', 'Shoulders'),

  // ── Additional Dumbbell ────────────────────────────────────────────────────

  seed('Dumbbell Preacher Curl',      'dumbbell', 'Biceps'),
  seed('Dumbbell Zottman Curl',       'dumbbell', 'Biceps'),
  seed('Dumbbell Rear Delt Row',      'dumbbell', 'Shoulders'),
  seed('Dumbbell Thruster',           'dumbbell', 'Full Body'),
  seed('Dumbbell Snatch',             'dumbbell', 'Full Body'),
  seed('Dumbbell Lateral Lunge',      'dumbbell', 'Quads'),
  seed('Dumbbell Good Morning',       'dumbbell', 'Hamstrings'),
  seed('Dumbbell Walking Lunge',      'dumbbell', 'Quads'),
  seed('Dumbbell Y-Raise',            'dumbbell', 'Shoulders'),
  seed('Lying Dumbbell Row',          'dumbbell', 'Back'),
  seed('Dumbbell Close-Grip Press',   'dumbbell', 'Triceps'),
  seed('Dumbbell Svend Press',        'dumbbell', 'Chest'),
  seed('Dumbbell Tate Press',         'dumbbell', 'Triceps'),
  seed('Dumbbell Single-Leg Deadlift','dumbbell', 'Hamstrings'),
  seed('Dumbbell Sumo Squat',         'dumbbell', 'Quads'),
  seed('Dumbbell Split Squat',        'dumbbell', 'Quads'),

  // ── Additional Machine ─────────────────────────────────────────────────────

  seed('Incline Chest Press Machine', 'machine', 'Chest'),
  seed('Decline Chest Press Machine', 'machine', 'Chest'),
  seed('Lateral Raise Machine',       'machine', 'Shoulders'),
  seed('Rear Delt Machine',           'machine', 'Shoulders'),
  seed('Bicep Curl Machine',          'machine', 'Biceps'),
  seed('Tricep Extension Machine',    'machine', 'Triceps'),
  seed('Rotary Torso Machine',        'machine', 'Core'),
  seed('Roman Chair Sit-Up',          'machine', 'Core'),
  seed('Roman Chair Hyperextension',  'machine', 'Lower Back'),
  seed('Incline Leg Press',           'machine', 'Quads'),
  seed('Glute Drive Machine',         'machine', 'Glutes'),
  seed('Hip Thrust Machine',          'machine', 'Glutes'),
  seed('Low Row Machine',             'machine', 'Back'),
  seed('High Row Machine',            'machine', 'Back'),
  seed('Shoulder Shrug Machine',      'machine', 'Traps'),
  seed('Diverging Lat Pulldown',      'machine', 'Back'),
  seed('Converging Chest Press',      'machine', 'Chest'),

  // ── Additional Cable ───────────────────────────────────────────────────────

  seed('Cable Crossover',             'cable', 'Chest'),
  seed('Kneeling Cable Crunch',       'cable', 'Core'),
  seed('Cable Drag Curl',             'cable', 'Biceps'),
  seed('Cable Reverse Curl',          'cable', 'Forearms'),
  seed('Cable Hammer Curl (Rope)',    'cable', 'Biceps'),
  seed('Cable Incline Fly',           'cable', 'Chest'),
  seed('Cable Decline Fly',           'cable', 'Chest'),
  seed('Half-Kneeling Cable Row',     'cable', 'Back'),
  seed('Cable Good Morning',          'cable', 'Hamstrings'),
  seed('Cable Concentration Curl',    'cable', 'Biceps'),
  seed('Cable Overhead Press',        'cable', 'Shoulders'),
  seed('Cable Rear Delt Row',         'cable', 'Shoulders'),
  seed('Cable Pallof Press',          'cable', 'Core'),
  seed('Cable Wrist Extension',       'cable', 'Forearms'),
  seed('Cable Sumo Deadlift',         'cable', 'Quads'),
  seed('Cable Close-Grip Row',        'cable', 'Back'),
  seed('Cable Wide-Grip Row',         'cable', 'Back'),

  // ── Additional Bodyweight ──────────────────────────────────────────────────

  seed('Ring Dip',                    'bodyweight', 'Chest'),
  seed('Ring Row',                    'bodyweight', 'Back'),
  seed('Typewriter Pull-Up',          'bodyweight', 'Back'),
  seed('Archer Pull-Up',              'bodyweight', 'Back'),
  seed('Chest-to-Bar Pull-Up',        'bodyweight', 'Back'),
  seed('Kipping Pull-Up',             'bodyweight', 'Back'),
  seed('Scapular Pull-Up',            'bodyweight', 'Back'),
  seed('Dead Hang',                   'bodyweight', 'Back'),
  seed('Active Hang',                 'bodyweight', 'Back'),
  seed('Tuck Jump',                   'bodyweight', 'Full Body'),
  seed('Lateral Lunge',               'bodyweight', 'Quads'),
  seed('Cossack Squat',               'bodyweight', 'Quads'),
  seed('Skater Squat',                'bodyweight', 'Quads'),
  seed('Sissy Squat',                 'bodyweight', 'Quads'),
  seed('Jefferson Curl',              'bodyweight', 'Hamstrings'),
  seed('Single-Leg Romanian Deadlift','bodyweight', 'Hamstrings'),
  seed('Reverse Nordic Curl',         'bodyweight', 'Quads'),
  seed('Glute-Ham Raise',             'bodyweight', 'Hamstrings'),
  seed('Copenhagen Plank',            'bodyweight', 'Core'),
  seed('Bear Crawl',                  'bodyweight', 'Full Body'),
  seed('Inchworm',                    'bodyweight', 'Full Body'),
  seed('Hip Airplane',                'bodyweight', 'Glutes'),
  seed('Tuck Planche Push-Up',        'bodyweight', 'Chest'),
  seed('Ring Muscle-Up',              'bodyweight', 'Back'),
  seed('Bar Muscle-Up',               'bodyweight', 'Back'),
  seed('V-Up',                        'bodyweight', 'Core'),
  seed('Windshield Wiper',            'bodyweight', 'Core'),
  seed('Toes to Bar',                 'bodyweight', 'Core'),
  seed('Knees to Chest',              'bodyweight', 'Core'),
  seed('Explosive Push-Up',           'bodyweight', 'Chest'),

  // ── Kettlebell ─────────────────────────────────────────────────────────────

  seed('Kettlebell Swing',            'kettlebell', 'Glutes'),
  seed('Kettlebell Single-Arm Swing', 'kettlebell', 'Glutes'),
  seed('Turkish Get-Up',              'kettlebell', 'Full Body'),
  seed('Kettlebell Goblet Squat',     'kettlebell', 'Quads'),
  seed('Kettlebell Deadlift',         'kettlebell', 'Back'),
  seed('Kettlebell Romanian Deadlift','kettlebell', 'Hamstrings'),
  seed('Kettlebell Sumo Deadlift',    'kettlebell', 'Quads'),
  seed('Kettlebell Clean',            'kettlebell', 'Full Body'),
  seed('Kettlebell Snatch',           'kettlebell', 'Full Body'),
  seed('Kettlebell Overhead Press',   'kettlebell', 'Shoulders'),
  seed('Kettlebell Push Press',       'kettlebell', 'Shoulders'),
  seed('Kettlebell Jerk',             'kettlebell', 'Shoulders'),
  seed('Kettlebell Row',              'kettlebell', 'Back'),
  seed('Kettlebell Windmill',         'kettlebell', 'Core'),
  seed('Kettlebell Figure-8',         'kettlebell', 'Core'),
  seed('Kettlebell Halo',             'kettlebell', 'Shoulders'),
  seed('Kettlebell Thruster',         'kettlebell', 'Full Body'),
  seed('Kettlebell Farmer\'s Carry',  'kettlebell', 'Full Body'),
  seed('Kettlebell Lunge',            'kettlebell', 'Quads'),
  seed('Kettlebell Lateral Lunge',    'kettlebell', 'Quads'),
  seed('Kettlebell Front Rack Squat', 'kettlebell', 'Quads'),
  seed('Kettlebell Hip Thrust',       'kettlebell', 'Glutes'),
  seed('Kettlebell Clean and Press',  'kettlebell', 'Full Body'),
  seed('Kettlebell Curl',             'kettlebell', 'Biceps'),
  seed('Kettlebell Skull Crusher',    'kettlebell', 'Triceps'),
  seed('Kettlebell Around the World', 'kettlebell', 'Core'),
  seed('Kettlebell Suitcase Deadlift','kettlebell', 'Back'),
  seed('Kettlebell Step-Up',          'kettlebell', 'Quads'),
  seed('Kettlebell Box Squat',        'kettlebell', 'Quads'),
  seed('Double Kettlebell Press',     'kettlebell', 'Shoulders'),

  // ── Band (Resistance Bands) ────────────────────────────────────────────────

  seed('Band Pull-Apart',             'band', 'Shoulders'),
  seed('Band Face Pull',              'band', 'Shoulders'),
  seed('Band Lateral Walk',           'band', 'Glutes'),
  seed('Band Clamshell',              'band', 'Glutes'),
  seed('Band Monster Walk',           'band', 'Glutes'),
  seed('Band Hip Thrust',             'band', 'Glutes'),
  seed('Band Glute Bridge',           'band', 'Glutes'),
  seed('Band Kickback',               'band', 'Glutes'),
  seed('Band Squat',                  'band', 'Quads'),
  seed('Band Deadlift',               'band', 'Back'),
  seed('Band Romanian Deadlift',      'band', 'Hamstrings'),
  seed('Band Good Morning',           'band', 'Hamstrings'),
  seed('Band Row',                    'band', 'Back'),
  seed('Band Pull-Down',              'band', 'Back'),
  seed('Band Pull-Through',           'band', 'Glutes'),
  seed('Band Overhead Press',         'band', 'Shoulders'),
  seed('Band Lateral Raise',          'band', 'Shoulders'),
  seed('Band Bicep Curl',             'band', 'Biceps'),
  seed('Band Hammer Curl',            'band', 'Biceps'),
  seed('Band Tricep Pushdown',        'band', 'Triceps'),
  seed('Band Overhead Extension',     'band', 'Triceps'),
  seed('Band Chest Press',            'band', 'Chest'),
  seed('Band Chest Fly',              'band', 'Chest'),
  seed('Band External Rotation',      'band', 'Shoulders'),
  seed('Band Internal Rotation',      'band', 'Shoulders'),
  seed('Band Woodchop',               'band', 'Core'),
  seed('Band Pallof Press',           'band', 'Core'),
  seed('Band Crunch',                 'band', 'Core'),
  seed('Band Lunge',                  'band', 'Quads'),
  seed('Band Step-Up',                'band', 'Quads'),

  // ── From free-exercise-db: Barbell ────────────────────────────────────────

  seed('Anti-Gravity Press',                                      'barbell', 'Shoulders'),
  seed('Barbell Ab Rollout - On Knees',                           'barbell', 'Core'),
  seed('Barbell Incline Shoulder Raise',                          'barbell', 'Shoulders'),
  seed('Barbell Rollout from Bench',                              'barbell', 'Core'),
  seed('Barbell Shrug Behind The Back',                           'barbell', 'Traps'),
  seed('Barbell Side Bend',                                       'barbell', 'Core'),
  seed('Board Press',                                             'barbell', 'Triceps'),
  seed('Car Drivers',                                             'barbell', 'Shoulders'),
  seed('Clean Deadlift',                                          'barbell', 'Hamstrings'),
  seed('Clean Pull',                                              'barbell', 'Quads'),
  seed('Clean Shrug',                                             'barbell', 'Traps'),
  seed('Clean from Blocks',                                       'barbell', 'Quads'),
  seed('Deadlift with Chains',                                    'barbell', 'Lower Back'),
  seed('Decline Close-Grip Bench To Skull Crusher',               'barbell', 'Triceps'),
  seed('Decline EZ Bar Triceps Extension',                        'barbell', 'Triceps'),
  seed('Elevated Back Lunge',                                     'barbell', 'Quads'),
  seed('Finger Curls',                                            'barbell', 'Forearms'),
  seed('Frankenstein Squat',                                      'barbell', 'Quads'),
  seed('Good Morning off Pins',                                   'barbell', 'Hamstrings'),
  seed('Hang Clean - Below the Knees',                            'barbell', 'Quads'),
  seed('Hang Snatch',                                             'barbell', 'Hamstrings'),
  seed('Hang Snatch - Below Knees',                               'barbell', 'Hamstrings'),
  seed('Heaving Snatch Balance',                                  'barbell', 'Quads'),
  seed('Incline Barbell Triceps Extension',                       'barbell', 'Triceps'),
  seed('Incline Bench Pull',                                      'barbell', 'Back'),
  seed('Jefferson Squats',                                        'barbell', 'Quads'),
  seed('Jerk Balance',                                            'barbell', 'Shoulders'),
  seed('Jerk Dip Squat',                                          'barbell', 'Quads'),
  seed('Kneeling Squat',                                          'barbell', 'Glutes'),
  seed("Landmine 180's",                                          'barbell', 'Core'),
  seed('Landmine Linear Jammer',                                  'barbell', 'Shoulders'),
  seed('Lying Cambered Barbell Row',                              'barbell', 'Back'),
  seed('Lying Close-Grip Barbell Triceps Extension Behind Head',  'barbell', 'Triceps'),
  seed('Lying High Bench Barbell Curl',                           'barbell', 'Biceps'),
  seed('Muscle Snatch',                                           'barbell', 'Hamstrings'),
  seed('One-Arm Side Deadlift',                                   'barbell', 'Quads'),
  seed('Palms-Down Wrist Curl Over A Bench',                      'barbell', 'Forearms'),
  seed('Palms-Up Barbell Wrist Curl Over A Bench',                'barbell', 'Forearms'),
  seed('Power Jerk',                                              'barbell', 'Quads'),
  seed('Press Sit-Up',                                            'barbell', 'Core'),
  seed('Rack Delivery',                                           'barbell', 'Shoulders'),
  seed('Reverse Band Deadlift',                                   'barbell', 'Lower Back'),
  seed('Reverse Band Power Squat',                                'barbell', 'Quads'),
  seed('Reverse Grip Bent-Over Row',                              'barbell', 'Back'),
  seed('Reverse Triceps Bench Press',                             'barbell', 'Triceps'),
  seed('Seated Barbell Twist',                                    'barbell', 'Core'),
  seed('Seated Palms-Down Barbell Wrist Curl',                    'barbell', 'Forearms'),
  seed('Single-Arm Linear Jammer',                                'barbell', 'Shoulders'),
  seed('Snatch Balance',                                          'barbell', 'Quads'),
  seed('Snatch Pull',                                             'barbell', 'Hamstrings'),
  seed('Snatch Shrug',                                            'barbell', 'Traps'),
  seed('Snatch from Blocks',                                      'barbell', 'Quads'),
  seed('Split Clean',                                             'barbell', 'Quads'),
  seed('Split Jerk',                                              'barbell', 'Quads'),
  seed('Split Snatch',                                            'barbell', 'Hamstrings'),
  seed('Squat Jerk',                                              'barbell', 'Quads'),
  seed('Squat with Chains',                                       'barbell', 'Quads'),
  seed('Straight Bar Bench Mid Row',                              'barbell', 'Back'),
  seed('Straight Raises on Incline Bench',                        'barbell', 'Shoulders'),
  seed('Wide-Grip Decline Barbell Pullover',                      'barbell', 'Chest'),
  seed('Wide Stance Barbell Squat',                               'barbell', 'Quads'),
  seed('Wide Stance Stiff Legs',                                  'barbell', 'Hamstrings'),

  // ── From free-exercise-db: Dumbbell ───────────────────────────────────────

  seed('Alternating Deltoid Raise',                               'dumbbell', 'Shoulders'),
  seed('Around The Worlds',                                       'dumbbell', 'Chest'),
  seed('Bent Over Dumbbell Rear Delt Raise With Head On Bench',   'dumbbell', 'Shoulders'),
  seed('Bent Over Two-Dumbbell Row With Palms In',                'dumbbell', 'Back'),
  seed('Cross Body Hammer Curl',                                  'dumbbell', 'Biceps'),
  seed('Cuban Press',                                             'dumbbell', 'Shoulders'),
  seed('Decline Dumbbell Fly',                                    'dumbbell', 'Chest'),
  seed('Dumbbell Incline Row',                                    'dumbbell', 'Back'),
  seed('Dumbbell Incline Shoulder Raise',                         'dumbbell', 'Shoulders'),
  seed('Dumbbell Lying Pronation',                                'dumbbell', 'Forearms'),
  seed('Dumbbell Lying Supination',                               'dumbbell', 'Forearms'),
  seed('Dumbbell Scaption',                                       'dumbbell', 'Shoulders'),
  seed('Dumbbell Side Bend',                                      'dumbbell', 'Core'),
  seed('Dumbbell Squat To A Bench',                               'dumbbell', 'Quads'),
  seed('Flexor Incline Dumbbell Curl',                            'dumbbell', 'Biceps'),
  seed('Incline Dumbbell Bench With Palms Facing In',             'dumbbell', 'Chest'),
  seed('Incline Dumbbell Fly With A Twist',                       'dumbbell', 'Chest'),
  seed('Incline Inner Biceps Curl',                               'dumbbell', 'Biceps'),
  seed('Iron Cross',                                              'dumbbell', 'Shoulders'),
  seed('Middle Back Shrug',                                       'dumbbell', 'Back'),
  seed('One-Arm Flat Bench Dumbbell Fly',                         'dumbbell', 'Chest'),
  seed('One-Arm Side Lateral',                                    'dumbbell', 'Shoulders'),
  seed('Palms-Down Dumbbell Wrist Curl Over A Bench',             'dumbbell', 'Forearms'),
  seed('Palms-Up Dumbbell Wrist Curl Over A Bench',               'dumbbell', 'Forearms'),
  seed('Power Partials',                                          'dumbbell', 'Shoulders'),
  seed('Reverse Fly',                                             'dumbbell', 'Shoulders'),
  seed('Reverse Fly With External Rotation',                      'dumbbell', 'Shoulders'),
  seed('Seated Dumbbell Palms-Down Wrist Curl',                   'dumbbell', 'Forearms'),
  seed('Seated Triceps Press',                                    'dumbbell', 'Triceps'),
  seed('See-Saw Press',                                           'dumbbell', 'Shoulders'),
  seed('Side Lateral to Front Raise',                             'dumbbell', 'Shoulders'),
  seed('Spell Caster',                                            'dumbbell', 'Core'),
  seed('Standing Alternating Dumbbell Press',                     'dumbbell', 'Shoulders'),
  seed('Standing Dumbbell Front Raise Above Head',                'dumbbell', 'Shoulders'),
  seed('Standing Palm-In One-Arm Dumbbell Press',                 'dumbbell', 'Shoulders'),
  seed('Vertical Swing',                                          'dumbbell', 'Hamstrings'),

  // ── From free-exercise-db: Machine ────────────────────────────────────────

  seed('Decline Smith Press',                                     'machine', 'Chest'),
  seed('Dip Machine',                                             'machine', 'Triceps'),
  seed('Leverage Deadlift',                                       'machine', 'Quads'),
  seed('Leverage Iso Row',                                        'machine', 'Back'),
  seed('Leverage Shrug',                                          'machine', 'Traps'),
  seed('Narrow Stance Leg Press',                                 'machine', 'Quads'),
  seed('Recumbent Bike',                                          'machine', 'Quads'),
  seed('Reverse Machine Fly',                                     'machine', 'Shoulders'),
  seed('Smith Machine Behind the Back Shrug',                     'machine', 'Traps'),
  seed('Smith Machine Bent Over Row',                             'machine', 'Back'),
  seed('Smith Machine Hip Raise',                                 'machine', 'Core'),
  seed('Smith Machine Leg Press',                                 'machine', 'Quads'),
  seed('Smith Machine Overhead Press',                            'machine', 'Shoulders'),
  seed('Smith Machine Reverse Calf Raise',                        'machine', 'Calves'),
  seed('Smith Machine Stiff-Legged Deadlift',                     'machine', 'Hamstrings'),
  seed('Narrow Stance Hack Squat',                                'machine', 'Quads'),

  // ── From free-exercise-db: Cable ──────────────────────────────────────────

  seed('Bent Over Low-Pulley Side Lateral',                       'cable', 'Shoulders'),
  seed('Cable Incline Pushdown',                                  'cable', 'Back'),
  seed('Cable Iron Cross',                                        'cable', 'Chest'),
  seed('Cable Judo Flip',                                         'cable', 'Core'),
  seed('Cable Reverse Crunch',                                    'cable', 'Core'),
  seed('Cable Rope Overhead Triceps Extension',                   'cable', 'Triceps'),
  seed('Cable Russian Twist',                                     'cable', 'Core'),
  seed('Elevated Cable Row',                                      'cable', 'Back'),
  seed('Flat Bench Cable Fly',                                    'cable', 'Chest'),
  seed('Full Range Lat Pulldown',                                 'cable', 'Back'),
  seed('High Cable Curl',                                         'cable', 'Biceps'),
  seed('Incline Cable Fly',                                       'cable', 'Chest'),
  seed('Kneeling Cable Crunch With Oblique Twist',                'cable', 'Core'),
  seed('Kneeling High Pulley Row',                                'cable', 'Back'),
  seed('Low Cable Crossover',                                     'cable', 'Chest'),
  seed('Low Pulley Row To Neck',                                  'cable', 'Shoulders'),
  seed('Lying Close-Grip Cable Curl',                             'cable', 'Biceps'),
  seed('One-Arm High-Pulley Cable Side Bend',                     'cable', 'Core'),
  seed('One-Legged Cable Kickback',                               'cable', 'Glutes'),
  seed('Overhead Cable Curl',                                     'cable', 'Biceps'),
  seed('Rope Straight-Arm Pulldown',                              'cable', 'Back'),
  seed('Seated Two-Arm Low-Pulley Wrist Curl',                    'cable', 'Forearms'),
  seed('Shotgun Row',                                             'cable', 'Back'),
  seed('Standing Cable Lift',                                     'cable', 'Core'),
  seed('Standing Low-Pulley Deltoid Raise',                       'cable', 'Shoulders'),
  seed('Standing Low-Pulley One-Arm Triceps Extension',           'cable', 'Triceps'),
  seed('Underhand Cable Pulldown',                                'cable', 'Back'),
  seed('V-Bar Pulldown',                                          'cable', 'Back'),
  seed('Wide-Grip Pulldown Behind The Neck',                      'cable', 'Back'),

  // ── From free-exercise-db: Bodyweight ─────────────────────────────────────

  seed('Air Bike',                                                'bodyweight', 'Core'),
  seed('Alternate Heel Touchers',                                 'bodyweight', 'Core'),
  seed('Bench Dips',                                              'bodyweight', 'Triceps'),
  seed('Bent-Knee Hip Raise',                                     'bodyweight', 'Core'),
  seed('Body-Up',                                                 'bodyweight', 'Triceps'),
  seed('Body Tricep Press',                                       'bodyweight', 'Triceps'),
  seed('Bottoms Up',                                              'bodyweight', 'Core'),
  seed('Butt-Ups',                                                'bodyweight', 'Core'),
  seed('Clock Push-Up',                                           'bodyweight', 'Chest'),
  seed('Cocoons',                                                 'bodyweight', 'Core'),
  seed('Cross-Body Crunch',                                       'bodyweight', 'Core'),
  seed('Crunch - Hands Overhead',                                 'bodyweight', 'Core'),
  seed('Dead Bug',                                                'bodyweight', 'Core'),
  seed('Decline Crunch',                                          'bodyweight', 'Core'),
  seed('Decline Oblique Crunch',                                  'bodyweight', 'Core'),
  seed('Decline Reverse Crunch',                                  'bodyweight', 'Core'),
  seed('Elbow to Knee',                                           'bodyweight', 'Core'),
  seed('Flat Bench Leg Pull-In',                                  'bodyweight', 'Core'),
  seed('Flat Bench Lying Leg Raise',                              'bodyweight', 'Core'),
  seed('Flutter Kicks',                                           'bodyweight', 'Glutes'),
  seed('Frog Sit-Up',                                             'bodyweight', 'Core'),
  seed('Gorilla Chin/Crunch',                                     'bodyweight', 'Core'),
  seed('Hanging Pike',                                            'bodyweight', 'Core'),
  seed('Hyperextension (No Bench)',                               'bodyweight', 'Lower Back'),
  seed('Incline Push-Up',                                         'bodyweight', 'Chest'),
  seed('Incline Push-Up Close-Grip',                              'bodyweight', 'Triceps'),
  seed('Incline Push-Up Reverse Grip',                            'bodyweight', 'Chest'),
  seed('Incline Push-Up Wide',                                    'bodyweight', 'Chest'),
  seed('Isometric Chest Squeeze',                                 'bodyweight', 'Chest'),
  seed('Isometric Neck - Front And Back',                         'bodyweight', 'Neck'),
  seed('Isometric Neck - Sides',                                  'bodyweight', 'Neck'),
  seed('Jackknife Sit-Up',                                        'bodyweight', 'Core'),
  seed('Janda Sit-Up',                                            'bodyweight', 'Core'),
  seed('Lateral Bound',                                           'bodyweight', 'Inner Thigh'),
  seed('Leg Lift',                                                'bodyweight', 'Glutes'),
  seed('Oblique Crunch',                                          'bodyweight', 'Core'),
  seed('Push-Up - Close Triceps Position',                        'bodyweight', 'Triceps'),
  seed('Push-Up With Feet Elevated',                              'bodyweight', 'Chest'),
  seed('Reverse Crunch',                                          'bodyweight', 'Core'),
  seed('Rocket Jump',                                             'bodyweight', 'Quads'),
  seed('Russian Twist',                                           'bodyweight', 'Core'),
  seed('Scissors Jump',                                           'bodyweight', 'Quads'),
  seed('Seated Leg Tuck',                                         'bodyweight', 'Core'),
  seed('Side Jackknife',                                          'bodyweight', 'Core'),
  seed('Spider Crawl',                                            'bodyweight', 'Core'),
  seed('Split Jump',                                              'bodyweight', 'Quads'),
  seed('Star Jump',                                               'bodyweight', 'Quads'),
  seed('Step-Up with Knee Raise',                                 'bodyweight', 'Glutes'),
  seed('Tuck Crunch',                                             'bodyweight', 'Core'),
  seed('Wide-Grip Rear Pull-Up',                                  'bodyweight', 'Back'),

  // ── From free-exercise-db: Kettlebell ─────────────────────────────────────

  seed('Alternating Hang Clean',                                  'kettlebell', 'Hamstrings'),
  seed('Alternating Kettlebell Press',                            'kettlebell', 'Shoulders'),
  seed('Alternating Kettlebell Row',                              'kettlebell', 'Back'),
  seed('Alternating Renegade Row',                                'kettlebell', 'Back'),
  seed('Bottoms-Up Clean From Hang',                              'kettlebell', 'Forearms'),
  seed('Double Kettlebell Alternating Hang Clean',                'kettlebell', 'Hamstrings'),
  seed('Extended Range One-Arm Kettlebell Floor Press',           'kettlebell', 'Chest'),
  seed('Kettlebell Dead Clean',                                   'kettlebell', 'Hamstrings'),
  seed('Kettlebell One-Legged Deadlift',                          'kettlebell', 'Hamstrings'),
  seed('Kettlebell Pass Between The Legs',                        'kettlebell', 'Core'),
  seed('Kettlebell Pirate Ships',                                 'kettlebell', 'Shoulders'),
  seed('Kettlebell Seesaw Press',                                 'kettlebell', 'Shoulders'),
  seed('Kettlebell Sumo High Pull',                               'kettlebell', 'Traps'),
  seed('Kettlebell Turkish Get-Up (Lunge Style)',                 'kettlebell', 'Shoulders'),
  seed('Kettlebell Turkish Get-Up (Squat Style)',                 'kettlebell', 'Shoulders'),
  seed('Lunge Pass Through',                                      'kettlebell', 'Hamstrings'),
  seed('One-Arm Kettlebell Military Press To Side',               'kettlebell', 'Shoulders'),
  seed('One-Arm Kettlebell Para Press',                           'kettlebell', 'Shoulders'),
  seed('One-Arm Kettlebell Split Jerk',                           'kettlebell', 'Shoulders'),
  seed('One-Arm Kettlebell Split Snatch',                         'kettlebell', 'Shoulders'),
  seed('One-Arm Open Palm Kettlebell Clean',                      'kettlebell', 'Hamstrings'),
  seed('Plyo Kettlebell Push-Up',                                 'kettlebell', 'Chest'),
  seed('Two-Arm Kettlebell Military Press',                       'kettlebell', 'Shoulders'),

  // ── From free-exercise-db: Band ───────────────────────────────────────────

  seed('Back Fly With Bands',                                     'band', 'Shoulders'),
  seed('Band Good Morning Pull-Through',                          'band', 'Hamstrings'),
  seed('Band Hip Adduction',                                      'band', 'Inner Thigh'),
  seed('Cable Calf Raise with Bands',                             'band', 'Calves'),
  seed('Cross Over With Bands',                                   'band', 'Chest'),
  seed('Hip Flexion with Band',                                   'band', 'Quads'),
  seed('Speed Band Overhead Triceps',                             'band', 'Triceps'),
]
